package java_project;

import java.sql.Connection;
import java_project.Main_Window;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Chamara Niroshana
 */
public class AdminPanel extends javax.swing.JFrame {
    /**
     * Creates new form AdminPanel
     */
String username;   
    public AdminPanel(String un) {
        initComponents();
        username=un;
        txtuser.setText(username);
    }

 //   AdminPanel(String text) {
 //       throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
 //   }

  /*  AdminPanel(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Hotel_Details = new javax.swing.JButton();
        Btn_Vehicle_Details = new javax.swing.JButton();
        Btn_Tour_Details = new javax.swing.JButton();
        txtuser = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lbl_tms = new javax.swing.JLabel();
        Btn_User_Details = new javax.swing.JButton();
        Btn_Payment_Details = new javax.swing.JButton();
        lbl_tms_ap = new javax.swing.JLabel();
        cmdlogout = new javax.swing.JButton();
        lbluser = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Hotel_Details.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btn_Hotel_Details.setText("Hotel Details");
        Btn_Hotel_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Hotel_DetailsActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Hotel_Details, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 120, -1));

        Btn_Vehicle_Details.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btn_Vehicle_Details.setText("Vehicle Details");
        Btn_Vehicle_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Vehicle_DetailsActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Vehicle_Details, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 120, -1));

        Btn_Tour_Details.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btn_Tour_Details.setText("Tour Details");
        Btn_Tour_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Tour_DetailsActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Tour_Details, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 120, -1));

        txtuser.setEditable(false);
        txtuser.setBackground(new java.awt.Color(204, 204, 204));
        txtuser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtuser.setForeground(new java.awt.Color(255, 255, 0));
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        getContentPane().add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 80, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_tms.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_tms.setForeground(new java.awt.Color(255, 0, 0));
        lbl_tms.setText("Admin Panel");
        jPanel1.add(lbl_tms, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        Btn_User_Details.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btn_User_Details.setText("User Details");
        Btn_User_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_User_DetailsActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_User_Details, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 120, -1));

        Btn_Payment_Details.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btn_Payment_Details.setText("Payment Details");
        Btn_Payment_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Payment_DetailsActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Payment_Details, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 120, -1));

        lbl_tms_ap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_tms_ap.setForeground(new java.awt.Color(255, 0, 0));
        lbl_tms_ap.setText("Tour Management System");
        jPanel1.add(lbl_tms_ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        cmdlogout.setBackground(new java.awt.Color(255, 0, 0));
        cmdlogout.setText("Logout");
        cmdlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(cmdlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        lbluser.setForeground(new java.awt.Color(255, 255, 255));
        lbluser.setText("Logged in as:");
        jPanel1.add(lbluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jButton1.setText("To iReport");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, -1));

        jButton2.setText("To iReport");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        jButton3.setText("To iReport");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        jButton4.setText("To iReport");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        jButton5.setText("To iReport");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Hotel_DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Hotel_DetailsActionPerformed
        // TODO add your handling code here:
        Hotels_Window m1 = new Hotels_Window();
        m1.setVisible(true);
        //this.dispose();
        
        
    }//GEN-LAST:event_Btn_Hotel_DetailsActionPerformed

    private void Btn_Vehicle_DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Vehicle_DetailsActionPerformed
        // TODO add your handling code here:
        Vehicles_Window m2 = new Vehicles_Window();
        m2.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_Btn_Vehicle_DetailsActionPerformed

    private void Btn_Tour_DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Tour_DetailsActionPerformed
        // TODO add your handling code here:
        Tour_Window m3 = new Tour_Window();
        m3.setVisible(true);
    }//GEN-LAST:event_Btn_Tour_DetailsActionPerformed

    private void cmdlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdlogoutActionPerformed
        Login la = new Login();
        la.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cmdlogoutActionPerformed

    private void Btn_User_DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_User_DetailsActionPerformed
        // TODO add your handling code here:
        User_Window u = new User_Window();
        u.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_Btn_User_DetailsActionPerformed

    private void Btn_Payment_DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Payment_DetailsActionPerformed
        // TODO add your handling code here:
        Payment_Window p=new Payment_Window(username);
        p.setVisible(true);
 //       this.dispose();
    }//GEN-LAST:event_Btn_Payment_DetailsActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            Connection con=DB.mycon();
            String irep1 ="E:\\TMSP Chamara Pavithra\\Java_Project\\src\\java_project\\tours.jrxml";
            JasperReport jr= JasperCompileManager.compileReport(irep1);
            JasperPrint pr=JasperFillManager.fillReport(jr, null,con);
            JasperViewer.viewReport(pr);
            
        }
        catch(Exception x){System.out.println(x);}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try
        {
            Connection con=DB.mycon();
            String irep1 ="E:\\TMSP Chamara Pavithra\\Java_Project\\src\\java_project\\vehicles.jrxml";
            JasperReport jr= JasperCompileManager.compileReport(irep1);
            JasperPrint pr=JasperFillManager.fillReport(jr, null,con);
            JasperViewer.viewReport(pr);
            
        }
        catch(Exception x){System.out.println(x);}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try
        {
            Connection con=DB.mycon();
            String irep1 ="E:\\TMSP Chamara Pavithra\\Java_Project\\src\\java_project\\hotels.jrxml";
            JasperReport jr= JasperCompileManager.compileReport(irep1);
            JasperPrint pr=JasperFillManager.fillReport(jr, null,con);
            JasperViewer.viewReport(pr);
            
        }
        catch(Exception x){System.out.println(x);}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
        {
            Connection con=DB.mycon();
            String irep1 ="E:\\TMSP Chamara Pavithra\\Java_Project\\src\\java_project\\payment.jrxml";
            JasperReport jr= JasperCompileManager.compileReport(irep1);
            JasperPrint pr=JasperFillManager.fillReport(jr, null,con);
            JasperViewer.viewReport(pr);
            
        }
        catch(Exception x){System.out.println(x);}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try
        {
            Connection con=DB.mycon();
            String irep1 ="E:\\TMSP Chamara Pavithra\\Java_Project\\src\\java_project\\user.jrxml";
            JasperReport jr= JasperCompileManager.compileReport(irep1);
            JasperPrint pr=JasperFillManager.fillReport(jr, null,con);
            JasperViewer.viewReport(pr);
            
        }
        catch(Exception x){System.out.println(x);}
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Hotel_Details;
    private javax.swing.JButton Btn_Payment_Details;
    private javax.swing.JButton Btn_Tour_Details;
    private javax.swing.JButton Btn_User_Details;
    private javax.swing.JButton Btn_Vehicle_Details;
    private javax.swing.JButton cmdlogout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_tms;
    private javax.swing.JLabel lbl_tms_ap;
    private javax.swing.JLabel lbluser;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
