/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package java_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.*;


public class UserPanel extends javax.swing.JFrame {
String place = "";
String vehicle = "";
String hotel = "";
int rs = 0;
int op;
static String username;

    
    public UserPanel(String un) {
        initComponents();
        username=un;
        txtuser.setText(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Place = new javax.swing.ButtonGroup();
        Vehicle = new javax.swing.ButtonGroup();
        Hotel = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        cmdlogout = new javax.swing.JButton();
        txtuser = new javax.swing.JTextField();
        lbluser = new javax.swing.JLabel();
        cmdcancel = new javax.swing.JButton();
        cmdpay = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtrs = new javax.swing.JTextField();
        txthotel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtplace = new javax.swing.JTextField();
        txtvehicle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmdselect = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        combo_nop = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        rbhotelaraliya = new javax.swing.JRadioButton();
        rbjetwin = new javax.swing.JRadioButton();
        rbhilton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbvan = new javax.swing.JRadioButton();
        rbcar = new javax.swing.JRadioButton();
        rbbus = new javax.swing.JRadioButton();
        rbanuradhapura = new javax.swing.JRadioButton();
        rbkandy = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rbnuwaraeliya = new javax.swing.JRadioButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(null);

        cmdlogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdlogout.setText("Logout");
        cmdlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdlogoutActionPerformed(evt);
            }
        });

        txtuser.setEditable(false);
        txtuser.setBackground(new java.awt.Color(204, 204, 204));
        txtuser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtuser.setForeground(new java.awt.Color(255, 0, 0));

        lbluser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbluser.setForeground(new java.awt.Color(255, 255, 255));
        lbluser.setText("Logged in as:");

        cmdcancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmdcancel.setForeground(new java.awt.Color(204, 0, 0));
        cmdcancel.setText("Clear");
        cmdcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcancelActionPerformed(evt);
            }
        });

        cmdpay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmdpay.setForeground(new java.awt.Color(204, 0, 0));
        cmdpay.setText("Pay");
        cmdpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdpayActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Vehicle");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Places");

        txtrs.setEditable(false);
        txtrs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtrs.setForeground(new java.awt.Color(255, 0, 0));

        txthotel.setEditable(false);
        txthotel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txthotel.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hotel");

        txtplace.setEditable(false);
        txtplace.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtplace.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtvehicle.setEditable(false);
        txtvehicle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtvehicle.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Your Selection");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Rs.");

        cmdselect.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmdselect.setForeground(new java.awt.Color(255, 0, 0));
        cmdselect.setText("Select");
        cmdselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdselectActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("No Of Passengers");

        combo_nop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo_nop.setForeground(new java.awt.Color(153, 153, 255));
        combo_nop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "1-5", "5-10", "10-15", "15-20" }));
        combo_nop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_nopActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Select Hotel");

        Hotel.add(rbhotelaraliya);
        rbhotelaraliya.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbhotelaraliya.setForeground(new java.awt.Color(0, 204, 51));
        rbhotelaraliya.setText("Hotel Araliya (Rs.1500)");
        rbhotelaraliya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbhotelaraliyaActionPerformed(evt);
            }
        });

        Hotel.add(rbjetwin);
        rbjetwin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbjetwin.setForeground(new java.awt.Color(0, 204, 51));
        rbjetwin.setText("Jetwin (Rs.2000)");

        Hotel.add(rbhilton);
        rbhilton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbhilton.setForeground(new java.awt.Color(0, 204, 51));
        rbhilton.setText("Hilton (Rs.3000)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Select Vehicle");

        Vehicle.add(rbvan);
        rbvan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbvan.setForeground(new java.awt.Color(0, 204, 255));
        rbvan.setText("Van (Rs.20000)");
        rbvan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbvanActionPerformed(evt);
            }
        });

        Vehicle.add(rbcar);
        rbcar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbcar.setForeground(new java.awt.Color(0, 204, 255));
        rbcar.setText("Car (Rs.30000)");

        Vehicle.add(rbbus);
        rbbus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbbus.setForeground(new java.awt.Color(0, 204, 255));
        rbbus.setText("Bus (Rs.40000)");

        Place.add(rbanuradhapura);
        rbanuradhapura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbanuradhapura.setForeground(new java.awt.Color(0, 51, 204));
        rbanuradhapura.setText("Anuradhapura");

        Place.add(rbkandy);
        rbkandy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbkandy.setForeground(new java.awt.Color(0, 51, 204));
        rbkandy.setText("Kandy");
        rbkandy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbkandyActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Select Places");

        Place.add(rbnuwaraeliya);
        rbnuwaraeliya.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbnuwaraeliya.setForeground(new java.awt.Color(0, 51, 204));
        rbnuwaraeliya.setText("Nuwara Eliya");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmdselect))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabel6)
                                .addGap(132, 132, 132)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)))
                        .addGap(111, 111, 111))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(txtplace, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(txtvehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbkandy)
                                            .addComponent(rbnuwaraeliya)
                                            .addComponent(rbanuradhapura))))
                                .addGap(77, 77, 77)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbvan)
                                            .addComponent(rbcar)
                                            .addComponent(rbbus)))
                                    .addComponent(jLabel3))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txthotel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbluser, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 4, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbhotelaraliya)
                                    .addComponent(rbjetwin)
                                    .addComponent(rbhilton)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtrs, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(combo_nop, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(444, 444, 444)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(cmdpay)
                        .addGap(17, 17, 17)
                        .addComponent(cmdcancel)
                        .addGap(233, 233, 233))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cmdlogout)
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdlogout)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbkandy)
                            .addGap(0, 0, 0)
                            .addComponent(rbnuwaraeliya)
                            .addGap(0, 0, 0)
                            .addComponent(rbanuradhapura))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbhotelaraliya)
                            .addGap(0, 0, 0)
                            .addComponent(rbjetwin)
                            .addGap(0, 0, 0)
                            .addComponent(rbhilton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(rbvan)
                        .addGap(1, 1, 1)
                        .addComponent(rbcar)
                        .addGap(0, 0, 0)
                        .addComponent(rbbus)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_nop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(3, 3, 3)
                .addComponent(cmdselect)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtvehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txthotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(31, 31, 31)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdpay)
                    .addComponent(cmdcancel))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbvanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbvanActionPerformed

    }//GEN-LAST:event_rbvanActionPerformed

    private void rbhotelaraliyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbhotelaraliyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbhotelaraliyaActionPerformed

    private void cmdselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdselectActionPerformed
        String nop = (String)combo_nop.getSelectedItem( );
        
        if(nop=="1-5"){
            op = 1;
        }
        else if(nop=="5-10"){
            op = 2;
        }
        else if(nop=="10-15"){
            op = 3;
        }
        else if(nop=="15-20"){
            op = 4;
        }
        
        if(rbkandy.isSelected())
        {
            place = "Kandy";
        }
        if(rbanuradhapura.isSelected())
        {
            place = "Anuradhapura";
        }
        if(rbnuwaraeliya.isSelected())
        {
            place = "Nuwara Eliya";
        }
        txtplace.setText(place);
        
        if(rbvan.isSelected())
        {
            vehicle = "Van";
        }
        if(rbcar.isSelected())
        {
            vehicle = "Car";
        }
        if(rbbus.isSelected())
        {
            vehicle = "Bus";
        }
        txtvehicle.setText(vehicle);
        
        if(rbhotelaraliya.isSelected())
        {
            hotel = "Hotel Araliya";
        }
        if(rbjetwin.isSelected())
        {
            hotel = "Jetwin";
        }
        if(rbhilton.isSelected())
        {
            hotel = "Hilton";
        }
        txthotel.setText(hotel);
        
        if(place == "Kandy")
        {
            rs=8000;
            if(vehicle == "Van")
            {
                rs=rs+20000;
                if(hotel =="Hotel Araliya")
                {
                    rs=rs+1500;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else if(hotel =="Jetwin")
                {
                    rs=rs+2000;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else if(hotel =="Hilton")
                {
                    rs=rs+3000;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Select a Hotel");
                }
            }
            else if(vehicle == "Bus")
            {
                rs=rs+40000;
                if(hotel =="Hotel Araliya")
                {
                    rs=rs+1500;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else if(hotel =="Jetwin")
                {
                    rs=rs+2000;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else if(hotel =="Hilton")
                {
                    rs=rs+3000;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Select a Hotel");
                }
            }
            else if(vehicle == "Car")
            {
                rs=rs+30000;
                if(hotel =="Hotel Araliya")
                {
                    rs=rs+1500;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else if(hotel =="Jetwin")
                {
                    rs=rs+2000;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else if(hotel =="Hilton")
                {
                    rs=rs+3000;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Select a Hotel");
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"Select a Vehicle");
            }
        }
        else if(place == "Anuradhapura")
        {
            rs=10000;
            if(vehicle == "Van")
            {
                rs=rs+20000;
                if(hotel =="Hotel Araliya")
                {
                    rs=rs+1500;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else if(hotel =="Jetwin")
                {
                    rs=rs+2000;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else if(hotel =="Hilton")
                {
                    rs=rs+3000;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Select a Hotel");
                }
            }
            else if(vehicle == "Bus")
            {
                rs=rs+40000;
                if(hotel =="Hotel Araliya")
                {
                    rs=rs+1500;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else if(hotel =="Jetwin")
                {
                    rs=rs+2000;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else if(hotel =="Hilton")
                {
                    rs=rs+3000;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Select a Hotel");
                }
            }
            else if(vehicle == "Car")
            {
                rs=rs+30000;
                if(hotel =="Hotel Araliya")
                {
                    rs=rs+1500;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else if(hotel =="Jetwin")
                {
                    rs=rs+2000;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else if(hotel =="Hilton")
                {
                    rs=rs+3000;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Select a Hotel");
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"Select a Vehicle");
            }
        }
        else if(place == "Nuwara Eliya")
        {
            rs=12000;
            if(vehicle == "Van")
            {
                rs=rs+20000;
                if(hotel =="Hotel Araliya")
                {
                    rs=rs+1500;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else if(hotel =="Jetwin")
                {
                    rs=rs+2000;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else if(hotel =="Hilton")
                {
                    rs=rs+3000;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Select a Hotel");
                }
            }
            else if(vehicle == "Bus")
            {
                rs=rs+40000;
                if(hotel =="Hotel Araliya")
                {
                    rs=rs+1500;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else if(hotel =="Jetwin")
                {
                    rs=rs+2000;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else if(hotel =="Hilton")
                {
                    rs=rs+3000;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Select a Hotel");
                }
            }
            else if(vehicle == "Car")
            {
                rs=rs+30000;
                if(hotel =="Hotel Araliya")
                {
                    rs=rs+1500;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else if(hotel =="Jetwin")
                {
                    rs=rs+2000;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else if(hotel =="Hilton")
                {
                    rs=rs+3000;
                    if(op==1){
                        rs=rs*2;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==2){
                        rs=rs*4;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==3){
                        rs=rs*6;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else if(op==4){
                        rs=rs*8;
                        txtrs.setText(String.valueOf(rs));
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Select the no of Pasangers");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Select a Hotel");
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"Select a Vehicle");
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Select a Place");
        }
        
    }//GEN-LAST:event_cmdselectActionPerformed

    private void rbkandyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbkandyActionPerformed
       
    }//GEN-LAST:event_rbkandyActionPerformed

    private void cmdcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcancelActionPerformed
        txtplace.setText("");
        txtvehicle.setText("");
        txthotel.setText("");
        txtrs.setText("");
        combo_nop.setSelectedIndex(0);
        
        Place.clearSelection();
        Hotel.clearSelection();
        Vehicle.clearSelection();
        
        place = "";
        hotel = "";
        vehicle = "";
        rs = 0;
        op = 0;
    }//GEN-LAST:event_cmdcancelActionPerformed

    private void cmdpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdpayActionPerformed
        
        if(!(txtrs.getText().equals(""))){
            Payment aa = new Payment(txtrs.getText(),txtplace.getText(),txtvehicle.getText(),txthotel.getText(),username);
            aa.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null,"Error");
        }
       
    }//GEN-LAST:event_cmdpayActionPerformed

    private void combo_nopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_nopActionPerformed
        
    }//GEN-LAST:event_combo_nopActionPerformed

    private void cmdlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdlogoutActionPerformed
        Login la = new Login();
        la.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cmdlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPanel(username).setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Hotel;
    private javax.swing.ButtonGroup Place;
    private javax.swing.ButtonGroup Vehicle;
    private javax.swing.JButton cmdcancel;
    private javax.swing.JButton cmdlogout;
    private javax.swing.JButton cmdpay;
    private javax.swing.JButton cmdselect;
    private javax.swing.JComboBox combo_nop;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbluser;
    private javax.swing.JRadioButton rbanuradhapura;
    private javax.swing.JRadioButton rbbus;
    private javax.swing.JRadioButton rbcar;
    private javax.swing.JRadioButton rbhilton;
    private javax.swing.JRadioButton rbhotelaraliya;
    private javax.swing.JRadioButton rbjetwin;
    private javax.swing.JRadioButton rbkandy;
    private javax.swing.JRadioButton rbnuwaraeliya;
    private javax.swing.JRadioButton rbvan;
    private javax.swing.JTextField txthotel;
    private javax.swing.JTextField txtplace;
    private javax.swing.JTextField txtrs;
    private javax.swing.JTextField txtuser;
    private javax.swing.JTextField txtvehicle;
    // End of variables declaration//GEN-END:variables
}
