package java_project;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Chamara Niroshana
 */
public class User_Register extends javax.swing.JFrame {
String email;
String tel;

    /**
     * Creates new form User_Register
     */
    public User_Register() {
        initComponents();
        
        txtUserName.setText("");
        txtPassword.setText("");
        txtName.setText("");
        txtAddress.setText("");
        txtNumber.setText("");
        txtMail.setText("");
        
    }

    User_Register(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(360, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Member Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 224, 32));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("User Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setText("Phone Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setText("E-Mail");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        txtUserName.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 177, -1));

        txtPassword.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 179, -1));

        txtName.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 179, -1));

        txtAddress.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 179, -1));

        txtNumber.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(txtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 179, -1));

        txtMail.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 179, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 90, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 91, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 80, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tour Managmet System");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(txtUserName.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Enter the Username");
        }
        
        else if(txtPassword.getText().isEmpty() | txtName.getText().isEmpty() | txtAddress.getText().isEmpty() | txtNumber.getText().isEmpty() | txtMail.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Fill all the Fields");
        }
          
        else
        {
            int x = JOptionPane.showConfirmDialog(this, "Do you wish to register ?");
            int ch=0;
            if(x==0){
                try
                {
                    
                    Connection c = DB.mycon();
                    Statement s = c.createStatement();
                    ResultSet rs = s.executeQuery("SELECT * FROM user");
                    
                    while(rs.next())
                    {
                        if(txtUserName.getText().equals(rs.getString("User_Name")))
                        {
                            JOptionPane.showMessageDialog(this,"User Name exists. please select a different user name");       
                            ch = 1;
                        }

                    }
                    
                    
                    if(ch!=1)
                    {
                        boolean e = false;
                        email = txtMail.getText();
                        
                        for(int z=0; z<email.length(); z++)
                        {
                            
                            if(email.charAt(z)=='@')
                            {
                                e = true;
                                
                            }
                            
                        }
                        tel = txtNumber.getText();
                        if(tel.length()==10)
                        {
                            if (e)
                            {
                                if(email.endsWith(".com")){
                                    s.executeUpdate("INSERT INTO user VALUES('"+txtUserName.getText()+"','"+txtPassword.getText()+"','"+txtName.getText()+"','"+txtAddress.getText()+"','"+txtNumber.getText()+"','"+txtMail.getText()+"','user')");
                                    JOptionPane.showMessageDialog(this,"Successfully Registered !");

                                    txtUserName.setText("");
                                    txtPassword.setText("");
                                    txtName.setText("");
                                    txtAddress.setText("");
                                    txtNumber.setText("");
                                    txtMail.setText("");

                                    Login g = new Login();
                                    g.setVisible(true);
                                    this.dispose();
                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(this,"Invalid email");
                                }
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(this,"Invalid email");
                            }
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(this,"Invalid Phone Number");
                        }
                    }
                }
                
                
                catch (Exception e)
                {
                   
                    if(ch!=1){
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this,"Database error.");
                    }
                }
            }
            else if (x==2)
            {
                txtUserName.setText("");
                txtPassword.setText("");
                txtName.setText("");
                txtAddress.setText("");
                txtNumber.setText("");
                txtMail.setText("");
            }
            else{}
        }
            
            
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Main_Window l1 = new Main_Window();
        l1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
